image: karsten13/magicmirror:develop
imagePullPolicy: Always

replicaCount: 1

 # This will use the default deployment strategy unless it is overriden
deploymentStrategy: {}

service:
  type: ClusterIP
#  type: NodePort
#  type: LoadBalancer
  port: 8080
#  nodePort: 31888
#  externalIP: 192.168.0.38

ingress:
  enabled: true
  path: "/mm"
  tls: false
#  subdomain: ""

# List of modules to install.
# For example:
modules:
  install:
    - "https://github.com/jclarke0000/MMM-DarkSkyForecast"
    - "https://github.com/sdetweil/MyCovid19"
# modules:
#   install: []

# Environment variables to attach to the pods
env:
  - name: TZ
    value: Europe/Berlin


secrets: {}
# specify secrets (better in own file)
#   darkSkyApi: XXXXXXXXXXXXXXXXXXXXXX