image: karsten13/magicmirror:develop
imagePullPolicy: Always

replicaCount: 1

# This will use the default deployment strategy unless it is overriden
deploymentStrategy: {}

# if running without ingress:
# run service as loadbalancer, your can access your MagicMirror under 192.168.0.38:8080
# service:
#   type: LoadBalancer
#   port: 8080
#   externalIPs:
#     - 192.168.0.38

service:
  type: ClusterIP
  port: 8080

ingress:
  # type: "nginx"
  type: "traefik"
  enabled: true
  hostname: ""
  path: "/mm"
  tls: false

# List of modules to install.
# For example:
modules:
  install:
    - "https://github.com/jclarke0000/MMM-DarkSkyForecast"
    - "https://github.com/sdetweil/MyCovid19"
# modules:
#   install: []

# Environment variables to attach to the pods
env:
  - name: TZ
    value: Europe/Berlin


secrets: {}
# specify secrets (better in own file)
#   darkSkyApi: XXXXXXXXXXXXXXXXXXXXXX