image: karsten13/magicmirror:latest
imagePullPolicy: Always

service:
  type: ClusterIP
#  type: NodePort
#  type: LoadBalancer
  port: 8080
#  nodePort: 31888
#  externalIP: 192.168.0.38

ingress:
  enabled: true
  path: "/mm"
#  subdomain: ""

# List of modules to install.
# For example:
modules:
 install:
   - "https://github.com/jclarke0000/MMM-DarkSkyForecast"
   - "https://github.com/sdetweil/MyCovid19"
# modules:
#   install: []
