apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "magicmirror.fullname" . }}-config
  labels:
    app: {{ template "magicmirror.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  config.js: |-
{{ tpl (.Files.Get "config/config.js") . | indent 4 }}
  custom.css: |-
{{ tpl (.Files.Get "css/custom.css") . | indent 4 }}
